# -*- coding: utf-8 -*-
"""1_アンケートデータ.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y47l8WDCg0Dk0oH5ZJEA7hlhQgUfdD-o

# よほほ〜い

## よっほほ〜い
"""

import altair as alt
from vega_datasets import data
cars = data.cars()

alt.Chart(cars).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
).interactive()